DELETE FROM INSIGHT.SE_UG_USER_GROUP WHERE UG_U_ID=(select U_ID from INSIGHT.SE_U_USER WHERE U_USERNAME='x007') AND UG_G_ID=(SELECT G_ID FROM INSIGHT.SE_G_GROUP WHERE G_DESCRIPTION='Full View Only');
