INSERT INTO INSIGHT.SE_UG_USER_GROUP (UG_U_ID,UG_G_ID)
VALUES ((select U_ID from INSIGHT.SE_U_USER WHERE U_USERNAME='x007'),(SELECT G_ID FROM INSIGHT.SE_G_GROUP WHERE G_DESCRIPTION='Administrator'));
